package com.morecritters.fabric.client.module.critter_atlas;

import com.morecritters.fabric.client.module.critter_atlas.AtlasPage.Button;
import com.morecritters.fabric.client.module.critter_atlas.AtlasPage.ButtonAction;
import com.morecritters.fabric.client.module.critter_atlas.AtlasPage.Model;
import com.morecritters.fabric.client.module.critter_atlas.AtlasPage.Picture;
import com.morecritters.fabric.client.module.critter_atlas.AtlasPage.Tooltip;
import com.morecritters.fabric.ids.ArmossilloIds;
import com.morecritters.fabric.ids.AvoiderIds;
import com.morecritters.fabric.ids.BlubberfishIds;
import com.morecritters.fabric.ids.BombJellyIds;
import com.morecritters.fabric.ids.BunbugIds;
import com.morecritters.fabric.ids.CorpseCrewIds;
import com.morecritters.fabric.ids.CreeblossomIds;
import com.morecritters.fabric.ids.CritterAtlasIds;
import com.morecritters.fabric.ids.CritterlingsAIds;
import com.morecritters.fabric.ids.CritterlingsBIds;
import com.morecritters.fabric.ids.CritterlingsCIds;
import com.morecritters.fabric.ids.CritterlingsDIds;
import com.morecritters.fabric.ids.CritterlingsEIds;
import com.morecritters.fabric.ids.CustodianIds;
import com.morecritters.fabric.ids.DripperIds;
import com.morecritters.fabric.ids.GravediggerIds;
import com.morecritters.fabric.ids.MiscIds;
import com.morecritters.fabric.ids.RamchuIds;
import com.morecritters.fabric.ids.ShriekbatIds;
import com.morecritters.fabric.ids.SnowflakeSpiderIds;
import com.morecritters.fabric.ids.StincarpIds;
import com.morecritters.fabric.ids.TreepletIds;
import com.morecritters.fabric.ids.WarptrapIds;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Every page of the critter atlas, keyed by the name of the original's menu without its
 * {@code critter_atlas_} prefix. Generated by {@code extract_pages.py} from the original screens,
 * button messages and procedures; edit the script, not this file.
 */
final class AtlasPages {
	static final String ROOT = "root_page";
	/** The closed book, shown when the atlas is used while sneaking. */
	static final String COVER = "view";

	private static final Map<String, AtlasPage> PAGES = new HashMap<>();

	static AtlasPage get(String name) {
		AtlasPage page = PAGES.get(name);
		if (page == null) throw new IllegalArgumentException("No critter atlas page " + name);
		return page;
	}

	private static void page(String name, int width, int height, List<Picture> pictures, List<Model> models,
			List<Tooltip> tooltips, List<Button> buttons) {
		PAGES.put(name, new AtlasPage(name, width, height, pictures, models, tooltips, buttons));
	}

	static {
		page("armossillo", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/regular_critter_background.png", 7, -2, 112, 100, null),
				new Picture("textures/screens/text_armossillo_1.png", 7, 101, 130, 44, null),
				new Picture("textures/screens/text_armossillo_2.png", 145, 2, 130, 152, null)),
			List.of(
				new Model(ArmossilloIds.Entities.ARMOSSILLO, 64, 81, 30, 32, Model.ALWAYS)),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("root_page_2")),
				new Button("textures/screens/atlas/imagebutton_arrow_right_1.png", 259, 147, 18, 10, new ButtonAction.TurnTo("armossillo_2"))));
		page("armossillo_2", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/text_armossillo_3.png", 4, 3, 130, 152, null)),
			List.of(),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("armossillo"))));
		page("avoider", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/regular_critter_background.png", 7, -2, 112, 100, null),
				new Picture("textures/screens/text_avoider_1.png", 4, 104, 130, 44, null),
				new Picture("textures/screens/text_avoider_2.png", 145, 2, 130, 152, null)),
			List.of(
				new Model(AvoiderIds.Entities.AVOIDER, 63, 63, 30, 14, Model.ALWAYS)),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("root_page")),
				new Button("textures/screens/atlas/imagebutton_arrow_right_1.png", 259, 147, 18, 10, new ButtonAction.TurnTo("avoider_2"))));
		page("avoider_2", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/text_avoider_3.png", 4, 2, 130, 152, null)),
			List.of(),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("avoider"))));
		page("balloon_rat", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/regular_critter_background.png", 7, -2, 112, 100, null),
				new Picture("textures/screens/text_balloon_rat_1.png", 4, 104, 130, 44, null),
				new Picture("textures/screens/text_balloon_rat_2.png", 146, 2, 130, 152, null)),
			List.of(
				new Model(CritterAtlasIds.Entities.MODEL_7, 61, 69, 35, 20, Model.ALWAYS)),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("root_page")),
				new Button("textures/screens/atlas/imagebutton_arrow_right_1.png", 259, 147, 18, 10, new ButtonAction.TurnTo("balloon_rat_2"))));
		page("balloon_rat_2", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/text_balloon_rat_3.png", 3, 2, 130, 152, null),
				new Picture("textures/screens/text_balloon_rat_4.png", 146, 2, 130, 152, null)),
			List.of(),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("balloon_rat"))));
		page("blubberfish", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/regular_critter_background.png", 7, -2, 112, 100, null),
				new Picture("textures/screens/text_blubberfish_1.png", 4, 104, 130, 44, null),
				new Picture("textures/screens/text_blubberfish_2.png", 145, 2, 132, 152, null)),
			List.of(
				new Model(BlubberfishIds.Entities.BLUBBERFISH, 63, 63, 30, 14, Model.ALWAYS)),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("root_page")),
				new Button("textures/screens/atlas/imagebutton_arrow_right_1.png", 259, 147, 18, 10, new ButtonAction.TurnTo("blubberfish_2"))));
		page("blubberfish_2", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/text_blubberfish_3.png", 3, 4, 130, 152, null)),
			List.of(),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("blubberfish"))));
		page("bomb_jelly", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/regular_critter_background.png", 7, -2, 112, 100, null),
				new Picture("textures/screens/text_bomb_jelly1.png", 4, 104, 130, 44, null),
				new Picture("textures/screens/text_bomb_jelly2.png", 147, 3, 130, 152, null)),
			List.of(
				// The original drew its unsized jelly here, with the medium jelly's model; that entity has no model of its own in this port.
				new Model(BombJellyIds.Entities.BOMB_JELLY_MEDIUM, 63, 63, 30, 14, Model.ALWAYS)),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("root_page"))));
		page("bouncelizard", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/regular_critter_background.png", 7, -2, 112, 100, null),
				new Picture("textures/screens/text_bouncelizard_1.png", 2, 102, 130, 44, null),
				new Picture("textures/screens/text_bouncelizard_2.png", 146, 2, 134, 152, null)),
			List.of(
				new Model(CritterAtlasIds.Entities.MODEL_1, 64, 72, 30, 23, Model.ALWAYS)),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("root_page"))));
		page("bunbug", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/regular_critter_background.png", 7, -2, 112, 100, null),
				new Picture("textures/screens/text_bunbug_1.png", 4, 102, 130, 44, null),
				new Picture("textures/screens/text_bunbug_2.png", 146, 3, 130, 152, null)),
			List.of(
				new Model(BunbugIds.Entities.BUNBUG, 64, 75, 30, 26, Model.ALWAYS)),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("root_page")),
				new Button("textures/screens/atlas/imagebutton_arrow_right_1.png", 259, 147, 18, 10, new ButtonAction.TurnTo("bunbug_2"))));
		page("bunbug_2", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/text_bunbug_3.png", 7, 3, 130, 152, null)),
			List.of(),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("bunbug"))));
		page("corpse_crew", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/text_corpse_crew_1.png", 4, 104, 130, 44, null),
				new Picture("textures/screens/text_corpse_crew_2.png", 144, 3, 130, 152, null),
				new Picture("textures/screens/miniboss_critter_background.png", 7, -2, 112, 100, null)),
			List.of(
				new Model(CorpseCrewIds.Entities.CORPSE_MATE, 62, 83, 30, 34, 0),
				new Model(CorpseCrewIds.Entities.CORPSE_QUARTERMASTER, 62, 83, 30, 34, 1),
				new Model(CorpseCrewIds.Entities.CORPSE_TANK, 62, 83, 30, 34, 2),
				new Model(CorpseCrewIds.Entities.CORPSE_CAPTAIN, 62, 83, 30, 34, 3),
				new Model(CorpseCrewIds.Entities.CORPSE_PARROT, 62, 83, 30, 34, 4),
				new Model(CorpseCrewIds.Entities.CORPSE_LOOKOUT, 62, 83, 30, 34, 5)),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("root_page_2")),
				new Button("textures/screens/atlas/imagebutton_arrow_right_1.png", 259, 147, 18, 10, new ButtonAction.TurnTo("corpse_crew_2")),
				new Button("textures/screens/atlas/imagebutton_num_button1_0.png", 121, -1, 10, 12, new ButtonAction.ShowTab(0)),
				new Button("textures/screens/atlas/imagebutton_num_button2_0.png", 121, 13, 10, 12, new ButtonAction.ShowTab(1)),
				new Button("textures/screens/atlas/imagebutton_num_button3_0.png", 121, 27, 10, 12, new ButtonAction.ShowTab(2)),
				new Button("textures/screens/atlas/imagebutton_num_button4_0.png", 121, 55, 10, 12, new ButtonAction.ShowTab(3)),
				new Button("textures/screens/atlas/imagebutton_num_button5_0.png", 121, 69, 10, 12, new ButtonAction.ShowTab(4)),
				new Button("textures/screens/atlas/imagebutton_num_button_6_0.png", 121, 41, 10, 12, new ButtonAction.ShowTab(5))));
		page("corpse_crew_2", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/text_corpse_crew_3.png", 4, 1, 130, 152, null),
				new Picture("textures/screens/text_corpse_crew_4.png", 144, 3, 130, 152, null)),
			List.of(),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("corpse_crew")),
				new Button("textures/screens/atlas/imagebutton_arrow_right_1.png", 259, 147, 18, 10, new ButtonAction.TurnTo("corpse_crew_3"))));
		page("corpse_crew_3", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/text_corpse_crew_5.png", 3, 2, 130, 152, null),
				new Picture("textures/screens/text_corpse_crew_6.png", 144, 3, 130, 152, null)),
			List.of(),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("corpse_crew_2")),
				new Button("textures/screens/atlas/imagebutton_arrow_right_1.png", 259, 147, 18, 10, new ButtonAction.TurnTo("corpse_crew_4"))));
		page("corpse_crew_4", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/text_corpse_crew_7.png", 3, 2, 130, 152, null)),
			List.of(),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("corpse_crew_3"))));
		page("creeblossom", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/regular_critter_background.png", 7, -2, 112, 100, null),
				new Picture("textures/screens/text_creeblossom_1.png", 3, 102, 130, 44, null),
				new Picture("textures/screens/text_creeblossom_2.png", 146, 2, 131, 152, null)),
			List.of(
				new Model(CreeblossomIds.Entities.CREEBLOSSOM, 61, 76, 30, 27, Model.ALWAYS)),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("root_page")),
				new Button("textures/screens/atlas/imagebutton_arrow_right_1.png", 259, 147, 18, 10, new ButtonAction.TurnTo("creeblossom_2"))));
		page("creeblossom_2", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/text_creeblossom_3.png", 3, 2, 131, 152, null)),
			List.of(),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("creeblossom"))));
		page("critterlings", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/critterling_background.png", 152, 5, 32, 32, null),
				new Picture("textures/screens/critterling_background.png", 193, 5, 32, 32, null),
				new Picture("textures/screens/critterling_background.png", 234, 5, 32, 32, null),
				new Picture("textures/screens/critterling_background.png", 152, 40, 32, 32, null),
				new Picture("textures/screens/critterling_background.png", 193, 40, 32, 32, null),
				new Picture("textures/screens/critterling_background.png", 234, 40, 32, 32, null),
				new Picture("textures/screens/critterling_background.png", 152, 75, 32, 32, null),
				new Picture("textures/screens/critterling_background.png", 193, 75, 32, 32, null),
				new Picture("textures/screens/critterling_background.png", 234, 75, 32, 32, null),
				new Picture("textures/screens/critterling_background.png", 152, 110, 32, 32, null),
				new Picture("textures/screens/critterling_background.png", 193, 110, 32, 32, null),
				new Picture("textures/screens/critterling_background.png", 234, 110, 32, 32, null),
				new Picture("textures/screens/checkmark.png", 183, 26, 8, 11, CritterlingsAIds.Entities.CUBEFROG),
				new Picture("textures/screens/checkmark.png", 224, 26, 8, 11, CritterlingsAIds.Entities.PLAINSWYRM),
				new Picture("textures/screens/checkmark.png", 265, 26, 8, 11, CritterlingsAIds.Entities.DUNGER),
				new Picture("textures/screens/checkmark.png", 183, 61, 8, 11, CritterlingsAIds.Entities.SNEK),
				new Picture("textures/screens/checkmark.png", 224, 61, 8, 11, CritterlingsBIds.Entities.EXPY),
				new Picture("textures/screens/checkmark.png", 265, 61, 8, 11, CritterlingsBIds.Entities.SCOWL),
				new Picture("textures/screens/checkmark.png", 183, 96, 8, 11, CritterlingsBIds.Entities.ROLLBALL),
				new Picture("textures/screens/checkmark.png", 224, 96, 8, 11, CritterlingsBIds.Entities.OPALCRAB),
				new Picture("textures/screens/checkmark.png", 265, 96, 8, 11, CritterlingsCIds.Entities.MOTHKID),
				new Picture("textures/screens/checkmark.png", 183, 131, 8, 11, CritterlingsCIds.Entities.GILLMUNCH),
				new Picture("textures/screens/checkmark.png", 224, 131, 8, 11, CritterlingsDIds.Entities.STALK),
				new Picture("textures/screens/checkmark.png", 265, 131, 8, 11, CritterlingsCIds.Entities.DOMINIC),
				new Picture("textures/screens/text_critterlings.png", 4, -3, 132, 152, null)),
			List.of(
				new Model(CritterlingsAIds.Entities.CUBEFROG, 168, 26, 30, -23, Model.ALWAYS),
				new Model(CritterlingsAIds.Entities.PLAINSWYRM, 209, 26, 30, -23, Model.ALWAYS),
				new Model(CritterlingsAIds.Entities.DUNGER, 250, 28, 30, -21, Model.ALWAYS),
				new Model(CritterlingsAIds.Entities.SNEK, 168, 62, 30, 13, Model.ALWAYS),
				new Model(CritterlingsBIds.Entities.EXPY, 209, 65, 30, 16, Model.ALWAYS),
				new Model(CritterlingsBIds.Entities.SCOWL, 250, 64, 30, 15, Model.ALWAYS),
				new Model(CritterlingsBIds.Entities.ROLLBALL, 168, 97, 30, 48, Model.ALWAYS),
				new Model(CritterlingsBIds.Entities.OPALCRAB, 209, 98, 30, 49, Model.ALWAYS),
				new Model(CritterlingsCIds.Entities.MOTHKID, 250, 100, 30, 51, Model.ALWAYS),
				new Model(CritterlingsCIds.Entities.GILLMUNCH, 168, 135, 30, 86, Model.ALWAYS),
				new Model(CritterlingsDIds.Entities.STALK, 209, 135, 30, 86, Model.ALWAYS),
				new Model(CritterlingsCIds.Entities.DOMINIC, 250, 135, 30, 86, Model.ALWAYS)),
			List.of(
				new Tooltip("gui.more_critters.critter_atlas_critterlings.tooltip_cubefrog_found_in_swamps", 156, 8, 180, 32),
				new Tooltip("gui.more_critters.critter_atlas_critterlings.tooltip_ssbplainswyrm_ss7found_in_plains", 197, 8, 221, 32),
				new Tooltip("gui.more_critters.critter_atlas_critterlings.tooltip_ssbdunger_ss7found_in_savannah_wa", 238, 8, 262, 32),
				new Tooltip("gui.more_critters.critter_atlas_critterlings.tooltip_ssbsnek_ss7found_in_desert_wagon", 156, 43, 180, 67),
				new Tooltip("gui.more_critters.critter_atlas_critterlings.tooltip_ssbexpy_ss7found_in_swamp_wagon", 197, 43, 221, 67),
				new Tooltip("gui.more_critters.critter_atlas_critterlings.tooltip_ssbscowl_ss7found_in_snowy_wagon", 238, 43, 262, 67),
				new Tooltip("gui.more_critters.critter_atlas_critterlings.tooltip_ssbrollbug_ss7found_in_swamps", 156, 78, 180, 102),
				new Tooltip("gui.more_critters.critter_atlas_critterlings.tooltip_ssbopalcrab_ss7found_in_ocean_wag", 197, 78, 221, 102),
				new Tooltip("gui.more_critters.critter_atlas_critterlings.tooltip_ssbmothkid_ss7found_in_taiga_wago", 238, 78, 262, 102),
				new Tooltip("gui.more_critters.critter_atlas_critterlings.tooltip_ssbgillmunch_ss7found_in_ghost_sh", 156, 113, 180, 137),
				new Tooltip("gui.more_critters.critter_atlas_critterlings.tooltip_ssbdominic_ss7found_in_closed_cri", 197, 113, 221, 137),
				new Tooltip("gui.more_critters.critter_atlas_critterlings.tooltip_ssbiolmer_ss7found_in_nauticrawl", 238, 113, 262, 137)),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("root_page")),
				new Button("textures/screens/atlas/imagebutton_arrow_right_11.png", 259, 147, 18, 10, new ButtonAction.TurnTo("critterlings_2"))));
		page("critterlings_2", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/critterling_background.png", 15, 5, 32, 32, null),
				new Picture("textures/screens/critterling_background.png", 56, 5, 32, 32, null),
				new Picture("textures/screens/critterling_background.png", 97, 5, 32, 32, null),
				new Picture("textures/screens/critterling_background.png", 15, 40, 32, 32, null),
				new Picture("textures/screens/critterling_background.png", 56, 40, 32, 32, null),
				new Picture("textures/screens/checkmark.png", 46, 26, 8, 11, CritterlingsCIds.Entities.OLMER),
				new Picture("textures/screens/checkmark.png", 87, 26, 8, 11, CritterlingsDIds.Entities.FLARG),
				new Picture("textures/screens/checkmark.png", 128, 26, 8, 11, CritterlingsDIds.Entities.PIRANHEED),
				new Picture("textures/screens/checkmark.png", 46, 61, 8, 11, CritterlingsDIds.Entities.MANGOTRICE),
				new Picture("textures/screens/checkmark.png", 87, 61, 8, 11, CritterlingsEIds.Entities.FRESNOID)),
			List.of(
				new Model(CritterlingsCIds.Entities.OLMER, 31, 30, 30, -19, Model.ALWAYS),
				new Model(CritterlingsDIds.Entities.FLARG, 71, 29, 30, -20, Model.ALWAYS),
				new Model(CritterlingsDIds.Entities.PIRANHEED, 113, 30, 30, -19, Model.ALWAYS),
				new Model(CritterlingsDIds.Entities.MANGOTRICE, 31, 65, 30, 16, Model.ALWAYS),
				new Model(CritterlingsEIds.Entities.FRESNOID, 72, 65, 30, 16, Model.ALWAYS)),
			List.of(
				new Tooltip("gui.more_critters.critter_atlas_critterlings_2.tooltip_ssbolmer_ss7found_in", 19, 8, 43, 32),
				new Tooltip("gui.more_critters.critter_atlas_critterlings_2.tooltip_ssbflarg_ss7found_in", 60, 8, 84, 32),
				new Tooltip("gui.more_critters.critter_atlas_critterlings_2.tooltip_ssbpiranheed_ss7found_in", 101, 8, 125, 32),
				new Tooltip("gui.more_critters.critter_atlas_critterlings_2.tooltip_ssbmangotrice_ss7found_in", 19, 43, 43, 67),
				new Tooltip("gui.more_critters.critter_atlas_critterlings_2.tooltip_ssbfresnoid_ss7found_in", 60, 43, 84, 67)),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("critterlings"))));
		page("custodian", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/regular_critter_background.png", 7, -2, 112, 100, null),
				new Picture("textures/screens/text_custodian_1.png", 7, 101, 130, 44, null),
				new Picture("textures/screens/text_custodian_2.png", 145, 2, 130, 152, null)),
			List.of(
				new Model(CustodianIds.Entities.CUSTODIAN, 64, 83, 20, 34, Model.ALWAYS)),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("root_page_2")),
				new Button("textures/screens/atlas/imagebutton_arrow_right_1.png", 259, 147, 18, 10, new ButtonAction.TurnTo("custodian_2"))));
		page("custodian_2", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/text_custodian_3.png", 4, 3, 130, 152, null),
				new Picture("textures/screens/text_custodian_4.png", 145, 4, 132, 152, null)),
			List.of(),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("custodian"))));
		page("dripper", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/regular_critter_background.png", 7, -2, 112, 100, null),
				new Picture("textures/screens/text_dripper_1.png", 7, 101, 130, 44, null),
				new Picture("textures/screens/text_dripper_2.png", 145, 2, 130, 152, null)),
			List.of(
				new Model(DripperIds.Entities.DRIPPER, 64, 74, 30, 25, Model.ALWAYS)),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("root_page_2"))));
		page("gravedigger", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/regular_critter_background.png", 7, -2, 112, 100, null),
				new Picture("textures/screens/text_gravedigger_1.png", 7, 101, 130, 44, null),
				new Picture("textures/screens/text_gravedigger_2.png", 145, 2, 130, 152, null)),
			List.of(
				new Model(GravediggerIds.Entities.GRAVEDIGGER, 64, 64, 30, 15, Model.ALWAYS)),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("root_page_2")),
				new Button("textures/screens/atlas/imagebutton_arrow_right_1.png", 259, 147, 18, 10, new ButtonAction.TurnTo("gravedigger_2"))));
		page("gravedigger_2", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/text_gravedigger_3.png", 4, 3, 130, 152, null)),
			List.of(),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("gravedigger"))));
		page("iropod", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/regular_critter_background.png", 7, -2, 112, 100, null),
				new Picture("textures/screens/text_iropod_1.png", 4, 104, 130, 44, null),
				new Picture("textures/screens/text_iropod_2.png", 145, 2, 130, 152, null)),
			List.of(
				new Model(CritterAtlasIds.Entities.MODEL_13, 63, 63, 30, 14, Model.ALWAYS)),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("root_page")),
				new Button("textures/screens/atlas/imagebutton_arrow_right_1.png", 259, 147, 18, 10, new ButtonAction.TurnTo("iropod_2"))));
		page("iropod_2", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/text_iropod_3.png", 4, 1, 130, 152, null)),
			List.of(),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("iropod"))));
		page("kelpire", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/regular_critter_background.png", 7, -2, 112, 100, null),
				new Picture("textures/screens/text_kelpire_1.png", 4, 104, 130, 44, null),
				new Picture("textures/screens/text_kelpire_2.png", 145, 2, 132, 152, null)),
			List.of(
				new Model(CritterAtlasIds.Entities.MODEL_15, 63, 63, 30, 14, Model.ALWAYS)),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("root_page"))));
		page("mightshroom", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/text_mightshroom_1.png", 4, 104, 130, 44, null),
				new Picture("textures/screens/text_mightshroom_2.png", 146, 2, 130, 152, null),
				new Picture("textures/screens/miniboss_critter_background.png", 7, -2, 112, 100, null)),
			List.of(
				new Model(CritterAtlasIds.Entities.MODEL_10, 63, 89, 20, 40, Model.ALWAYS)),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("root_page")),
				new Button("textures/screens/atlas/imagebutton_arrow_right_1.png", 259, 147, 18, 10, new ButtonAction.TurnTo("mightshroom_2"))));
		page("mightshroom_2", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/text_mightshroom_3.png", 5, 1, 130, 152, null),
				new Picture("textures/screens/text_mightshroom_4.png", 146, 2, 130, 152, null)),
			List.of(),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("mightshroom")),
				new Button("textures/screens/atlas/imagebutton_arrow_right_1.png", 259, 147, 18, 10, new ButtonAction.TurnTo("mightshroom_3"))));
		page("mightshroom_3", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/text_mightshroom_5.png", 4, 1, 130, 152, null),
				new Picture("textures/screens/text_mightshroom_6.png", 144, 0, 130, 152, null)),
			List.of(),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("mightshroom_2"))));
		page("nauticrawl", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/regular_critter_background.png", 7, -2, 112, 100, null),
				new Picture("textures/screens/text_nauticrawl_1.png", 4, 104, 130, 44, null),
				new Picture("textures/screens/text_nauticrawl_2.png", 145, 2, 132, 152, null)),
			List.of(
				new Model(CritterAtlasIds.Entities.MODEL_16, 63, 77, 30, 28, Model.ALWAYS)),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("root_page")),
				new Button("textures/screens/atlas/imagebutton_arrow_right_1.png", 259, 147, 18, 10, new ButtonAction.TurnTo("nauticrawl_2"))));
		page("nauticrawl_2", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/text_nauticrawl_3.png", 6, 1, 130, 152, null),
				new Picture("textures/screens/text_nauticrawl_4.png", 150, 3, 130, 152, null)),
			List.of(),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("nauticrawl"))));
		page("nervoid", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/regular_critter_background.png", 7, -2, 112, 100, null),
				new Picture("textures/screens/text_nervoid_1.png", 4, 104, 130, 44, null),
				new Picture("textures/screens/text_nervoid_2.png", 144, 3, 130, 152, null)),
			List.of(
				new Model(CritterAtlasIds.Entities.MODEL_19, 63, 79, 30, 30, Model.ALWAYS)),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("root_page_2")),
				new Button("textures/screens/atlas/imagebutton_arrow_right_1.png", 259, 147, 18, 10, new ButtonAction.TurnTo("nervoid_2"))));
		page("nervoid_2", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/text_nervoid_3.png", 5, 1, 130, 152, null),
				new Picture("textures/screens/text_nervoid_4.png", 144, 3, 130, 152, null)),
			List.of(),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("nervoid"))));
		page("ramchu", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/regular_critter_background.png", 7, -2, 112, 100, null),
				new Picture("textures/screens/text_ramchu_1.png", 7, 101, 130, 44, null),
				new Picture("textures/screens/text_ramchu_2.png", 145, 2, 131, 152, null)),
			List.of(
				new Model(RamchuIds.Entities.RAMCHU, 64, 61, 30, 12, Model.ALWAYS)),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("root_page_2")),
				new Button("textures/screens/atlas/imagebutton_arrow_right_1.png", 259, 147, 18, 10, new ButtonAction.TurnTo("ramchu_2"))));
		page("ramchu_2", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/text_ramchu_3.png", 4, 3, 130, 152, null)),
			List.of(),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("ramchu"))));
		page("root_page", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/text_root.png", 6, 3, 130, 152, null)),
			List.of(),
			List.of(
				new Tooltip("gui.more_critters.critter_atlas_root_page.tooltip_bunbug", 149, 12, 173, 36),
				new Tooltip("gui.more_critters.critter_atlas_root_page.tooltip_snowflake_spider", 179, 12, 203, 36),
				new Tooltip("gui.more_critters.critter_atlas_root_page.tooltip_shriekbat", 209, 12, 233, 36),
				new Tooltip("gui.more_critters.critter_atlas_root_page.tooltip_creeblossom", 239, 12, 263, 36),
				new Tooltip("gui.more_critters.critter_atlas_root_page.tooltip_bouncelizard", 149, 42, 173, 66),
				new Tooltip("gui.more_critters.critter_atlas_root_page.tooltip_stincarp", 179, 42, 203, 66),
				new Tooltip("gui.more_critters.critter_atlas_root_page.tooltip_balloon_rat", 209, 42, 233, 66),
				new Tooltip("gui.more_critters.critter_atlas_root_page.tooltip_warptrap", 239, 42, 263, 66),
				new Tooltip("gui.more_critters.critter_atlas_root_page.tooltip_shimmerwing", 149, 72, 173, 96),
				new Tooltip("gui.more_critters.critter_atlas_root_page.tooltip_mightshroom", 179, 72, 203, 96),
				new Tooltip("gui.more_critters.critter_atlas_root_page.tooltip_bomb_jelly", 209, 72, 233, 96),
				new Tooltip("gui.more_critters.critter_atlas_root_page.tooltip_avoider", 239, 72, 263, 96),
				new Tooltip("gui.more_critters.critter_atlas_root_page.tooltip_iropod", 149, 103, 173, 127),
				new Tooltip("gui.more_critters.critter_atlas_root_page.tooltip_blubberfish", 179, 103, 203, 127),
				new Tooltip("gui.more_critters.critter_atlas_root_page.tooltip_kelpire", 209, 103, 233, 127),
				new Tooltip("gui.more_critters.critter_atlas_root_page.tooltip_nauticrawl", 239, 103, 263, 127),
				new Tooltip("gui.more_critters.critter_atlas_root_page.tooltip_critterlings", 146, 131, 170, 155)),
			List.of(
				new Button("textures/screens/atlas/imagebutton_button_bunbug_0.png", 149, 11, 24, 26, new ButtonAction.TurnTo("bunbug")),
				new Button("textures/screens/atlas/imagebutton_button_snowflake_spider_0.png", 179, 11, 24, 26, new ButtonAction.TurnTo("snowflake_spider")),
				new Button("textures/screens/atlas/imagebutton_button_shriekbat_0.png", 209, 11, 24, 26, new ButtonAction.TurnTo("shriekbat")),
				new Button("textures/screens/atlas/imagebutton_button_creeblossom_0.png", 239, 11, 24, 26, new ButtonAction.TurnTo("creeblossom")),
				new Button("textures/screens/atlas/imagebutton_button_bouncelizard_0.png", 149, 41, 24, 26, new ButtonAction.TurnTo("bouncelizard")),
				new Button("textures/screens/atlas/imagebutton_button_stincarp_0.png", 179, 41, 24, 26, new ButtonAction.TurnTo("stincarp")),
				new Button("textures/screens/atlas/imagebutton_button_balloon_rat_0.png", 209, 41, 24, 26, new ButtonAction.TurnTo("balloon_rat")),
				new Button("textures/screens/atlas/imagebutton_button_warptrap_0.png", 239, 41, 24, 26, new ButtonAction.TurnTo("warptrap")),
				new Button("textures/screens/atlas/imagebutton_button_shimmerwing_0.png", 149, 71, 24, 26, new ButtonAction.TurnTo("shimmerwing")),
				new Button("textures/screens/atlas/imagebutton_button_mightshroom_0.png", 179, 71, 24, 26, new ButtonAction.TurnTo("mightshroom")),
				new Button("textures/screens/atlas/imagebutton_button_bomb_jelly_1.png", 209, 71, 24, 26, new ButtonAction.TurnTo("bomb_jelly")),
				new Button("textures/screens/atlas/imagebutton_button_avoider_1.png", 239, 71, 24, 26, new ButtonAction.TurnTo("avoider")),
				new Button("textures/screens/atlas/imagebutton_button_iropod_1.png", 149, 102, 24, 26, new ButtonAction.TurnTo("iropod")),
				new Button("textures/screens/atlas/imagebutton_button_blubberfish_1.png", 179, 102, 24, 26, new ButtonAction.TurnTo("blubberfish")),
				new Button("textures/screens/atlas/imagebutton_button_kelpire_1.png", 209, 102, 24, 26, new ButtonAction.TurnTo("kelpire")),
				new Button("textures/screens/atlas/imagebutton_button_nauticrawl_1.png", 239, 102, 24, 26, new ButtonAction.TurnTo("nauticrawl")),
				new Button("textures/screens/atlas/imagebutton_arrow_right_1.png", 254, 141, 18, 10, new ButtonAction.TurnTo("root_page_2")),
				new Button("textures/screens/atlas/imagebutton_button_critterling_0.png", 149, 133, 17, 19, new ButtonAction.TurnTo("critterlings")),
				new Button("textures/screens/atlas/imagebutton_partyhat_icon1.png", -11, -13, 17, 17, new ButtonAction.PlaySound(MiscIds.Sounds.ENTITY_ANNIVETERAN_DEATH))));
		page("root_page_2", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null)),
			List.of(),
			List.of(
				new Tooltip("gui.more_critters.critter_atlas_root_page_2.tooltip_shadelet", 16, 12, 40, 36),
				new Tooltip("gui.more_critters.critter_atlas_root_page_2.tooltip_treeplet", 47, 12, 71, 36),
				new Tooltip("gui.more_critters.critter_atlas_root_page_2.tooltip_nervoid", 78, 12, 102, 36),
				new Tooltip("gui.more_critters.critter_atlas_root_page_2.tooltip_corpse_crew", 109, 12, 133, 36),
				new Tooltip("gui.more_critters.critter_atlas_root_page_2.tooltip_gravedigger", 16, 42, 40, 66),
				new Tooltip("gui.more_critters.critter_atlas_root_page_2.tooltip_armossillo", 47, 42, 71, 66),
				new Tooltip("gui.more_critters.critter_atlas_root_page_2.tooltip_ramchu", 78, 42, 102, 66),
				new Tooltip("gui.more_critters.critter_atlas_root_page_2.tooltip_dripper", 109, 42, 133, 66),
				new Tooltip("gui.more_critters.critter_atlas_root_page_2.tooltip_custodian", 16, 72, 40, 96)),
			List.of(
				new Button("textures/screens/atlas/imagebutton_button_shadelet_0.png", 16, 11, 24, 26, new ButtonAction.TurnTo("shadelet")),
				new Button("textures/screens/atlas/imagebutton_button_treeplet_0.png", 47, 11, 24, 26, new ButtonAction.TurnTo("treeplet")),
				new Button("textures/screens/atlas/imagebutton_button_nervoid_0.png", 78, 11, 24, 26, new ButtonAction.TurnTo("nervoid")),
				new Button("textures/screens/atlas/imagebutton_button_corpse_crew_0.png", 109, 11, 24, 26, new ButtonAction.TurnTo("corpse_crew")),
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 6, 142, 18, 10, new ButtonAction.TurnTo("root_page")),
				new Button("textures/screens/atlas/imagebutton_button_gravedigger_0.png", 16, 41, 24, 26, new ButtonAction.TurnTo("gravedigger")),
				new Button("textures/screens/atlas/imagebutton_button_armossillo_0.png", 47, 41, 24, 26, new ButtonAction.TurnTo("armossillo")),
				new Button("textures/screens/atlas/imagebutton_button_ramchu_0.png", 78, 41, 24, 26, new ButtonAction.TurnTo("ramchu")),
				new Button("textures/screens/atlas/imagebutton_button_dripper_0.png", 109, 41, 24, 26, new ButtonAction.TurnTo("dripper")),
				new Button("textures/screens/atlas/imagebutton_button_custodian_0.png", 16, 71, 24, 26, new ButtonAction.TurnTo("custodian"))));
		page("shadelet", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/regular_critter_background.png", 7, -2, 112, 100, null),
				new Picture("textures/screens/text_shadelet_1.png", 4, 104, 130, 44, null),
				new Picture("textures/screens/text_shadelet_2.png", 144, 2, 130, 152, null)),
			List.of(
				new Model(CritterAtlasIds.Entities.MODEL_17, 63, 63, 35, 14, Model.ALWAYS)),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("root_page_2")),
				new Button("textures/screens/atlas/imagebutton_arrow_right_1.png", 259, 147, 18, 10, new ButtonAction.TurnTo("shadelet_2"))));
		page("shadelet_2", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/text_shadelet_3.png", 5, 3, 130, 152, null)),
			List.of(),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("shadelet"))));
		page("shimmerwing", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/regular_critter_background.png", 7, -2, 112, 100, null),
				new Picture("textures/screens/text_shimmerwing_1.png", 3, 105, 130, 44, null),
				new Picture("textures/screens/text_shimmerwing_2.png", 146, 2, 130, 152, null)),
			List.of(
				new Model(CritterAtlasIds.Entities.MODEL_9, 62, 68, 40, 19, Model.ALWAYS)),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("root_page")),
				new Button("textures/screens/atlas/imagebutton_arrow_right_1.png", 259, 147, 18, 10, new ButtonAction.TurnTo("shimmerwing_2"))));
		page("shimmerwing_2", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/text_shimmerwing_3.png", 3, 0, 130, 152, null)),
			List.of(),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("shimmerwing"))));
		page("shriekbat", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/regular_critter_background.png", 7, -2, 112, 100, null),
				new Picture("textures/screens/text_shriekbat_1.png", 4, 102, 130, 44, null),
				new Picture("textures/screens/text_shriekbat_2.png", 145, 2, 130, 152, null)),
			List.of(
				new Model(ShriekbatIds.Entities.SHRIEKBAT, 64, 57, 25, 8, Model.ALWAYS)),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("root_page")),
				new Button("textures/screens/atlas/imagebutton_arrow_right_1.png", 259, 147, 18, 10, new ButtonAction.TurnTo("shriekbat_2"))));
		page("shriekbat_2", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/text_shriekbat_3.png", 4, 3, 130, 152, null)),
			List.of(),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("shriekbat"))));
		page("snowflake_spider", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/regular_critter_background.png", 7, -2, 112, 100, null),
				new Picture("textures/screens/text_snowflake_spider_1.png", 4, 102, 130, 44, null),
				new Picture("textures/screens/text_snowflake_spider_2.png", 145, 2, 131, 152, null)),
			List.of(
				new Model(SnowflakeSpiderIds.Entities.SNOWFLAKE_SPIDER, 63, 75, 30, 26, Model.ALWAYS)),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("root_page")),
				new Button("textures/screens/atlas/imagebutton_arrow_right_1.png", 259, 147, 18, 10, new ButtonAction.TurnTo("snowflake_spider_2"))));
		page("snowflake_spider_2", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/text_snowflake_spider_3.png", 3, 0, 131, 152, null)),
			List.of(),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("snowflake_spider"))));
		page("stincarp", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/regular_critter_background.png", 7, -2, 112, 100, null),
				new Picture("textures/screens/text_stincarp_1.png", 4, 104, 130, 44, null),
				new Picture("textures/screens/text_stincarp_2.png", 146, 2, 130, 152, null)),
			List.of(
				new Model(StincarpIds.Entities.STINCARP, 65, 63, 28, 14, Model.ALWAYS)),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("root_page")),
				new Button("textures/screens/atlas/imagebutton_arrow_right_1.png", 259, 147, 18, 10, new ButtonAction.TurnTo("stincarp_2"))));
		page("stincarp_2", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/text_stincarp_3.png", 3, 1, 130, 152, null)),
			List.of(),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("stincarp"))));
		page("treeplet", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/regular_critter_background.png", 7, -2, 112, 100, null),
				new Picture("textures/screens/text_treeplet_1.png", 4, 104, 130, 44, null),
				new Picture("textures/screens/text_treeplet_2.png", 144, 3, 130, 152, null)),
			List.of(
				new Model(TreepletIds.Entities.TREEPLET, 63, 82, 30, 33, Model.ALWAYS)),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("root_page_2")),
				new Button("textures/screens/atlas/imagebutton_arrow_right_1.png", 259, 147, 18, 10, new ButtonAction.TurnTo("treeplet_2"))));
		page("treeplet_2", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/text_treeplet_3.png", 4, 2, 130, 152, null)),
			List.of(),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("treeplet"))));
		page("view", 176, 166,
			List.of(),
			List.of(
				new Model(CritterAtlasIds.Entities.CRITTER_ATLAS_MODEL, 88, 101, 75, 52, Model.ALWAYS)),
			List.of(),
			List.of());
		page("warptrap", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/regular_critter_background.png", 7, -2, 112, 100, null),
				new Picture("textures/screens/text_warptrap_1.png", 4, 104, 130, 44, null),
				new Picture("textures/screens/text_warptrap_2.png", 145, 2, 130, 152, null)),
			List.of(
				new Model(WarptrapIds.Entities.WARPTRAP, 64, 52, 30, 3, Model.ALWAYS)),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("root_page")),
				new Button("textures/screens/atlas/imagebutton_arrow_right_1.png", 259, 147, 18, 10, new ButtonAction.TurnTo("warptrap_2"))));
		page("warptrap_2", 280, 166,
			List.of(
				new Picture("textures/screens/critter_atlas_open_2.png", -4, -6, 287, 178, null),
				new Picture("textures/screens/text_warptrap_3.png", 3, 0, 130, 152, null)),
			List.of(),
			List.of(),
			List.of(
				new Button("textures/screens/atlas/imagebutton_arrow_left_1.png", 2, 147, 18, 10, new ButtonAction.TurnTo("warptrap"))));
	}

	private AtlasPages() {}
}
