package com.morecritters.fabric.module.misc;

import java.util.List;

/**
 * The items of the "More Critters" creative tab, in the original mod's order. Technical items
 * (atlas icons, partly eaten food, the invisible glow block, ...) are left out, as in the original.
 * Ids no module registers are skipped when the tab is filled.
 */
final class MoreCrittersTabContents {
	static final List<String> ITEMS = List.of(
		"critter_atlas", "wandering_collector_spawn_egg", "evolutioner_spawn_egg", "carrybug_spawn_egg", "bunbug_spawn_egg",
		"snowflake_spider_spawn_egg", "shriekbat_spawn_egg", "creeblossom_spawn_egg", "bouncelizard_spawn_egg",
		"stincarp_spawn_egg", "balloon_rat_spawn_egg", "warptrap_spawn_egg", "shimmerwing_spawn_egg", "mightshroom_spawn_egg",
		"bomb_jelly_spawn_egg", "avoider_spawn_egg", "iropod_spawn_egg", "blubberfish_spawn_egg", "kelpire_spawn_egg",
		"nauticrawl_spawn_egg", "shadelet_spawn_egg", "treeplet_spawn_egg", "nervoid_spawn_egg", "corpse_crew_spawn_egg",
		"gravedigger_spawn_egg", "armossillo_spawn_egg", "ramchu_spawn_egg", "dripper_spawn_egg", "custodian_spawn_egg",
		"bunbug_eggs", "raw_bunbug_meat", "cooked_bunbug_meat", "bunbug_burger", "bunbug_caviar", "bunbug_crust",
		"bunbug_crust_iced_sugar", "bunbug_crust_iced_chocolate", "sprinkles", "bunbug_crust_iced_sugar_sprinkled",
		"bunbug_crust_iced_chocolate_sprinkled", "bunbug_crust_iced_sugar_sprinkled_sweet_berries", "bunbug_crust_iced_sugar_sprinkled_glow_berries",
		"bunbug_crust_iced_sugar_sprinkled_bounceberries", "bunbug_crust_iced_chocolate_sprinkled_sweet_berries",
		"bunbug_crust_iced_chocolate_sprinkled_glow_berries", "bunbug_crust_iced_chocolate_sprinkled_bounceberries",
		"sackof_freezing", "freezing_string", "web_sack", "freezing_cobweb", "coldstone", "coldstone_stairs", "coldstone_slab",
		"coldstone_wall", "coldstone_bricks", "coldstone_brick_stairs", "coldstone_brick_slab", "coldstone_brick_wall",
		"polished_coldstone", "polished_coldstone_stairs", "polished_coldstone_slab", "polished_coldstone_wall",
		"chiseled_coldstone", "shriekbat_wing", "shriek_bomb", "shriekbat_soup", "blossombush_seed", "blossombush",
		"closed_blossombush", "bouncelizard_egg", "cooked_bouncelizard_egg", "bounceberry_bush_empty", "bounceberry",
		"bounceberry_jam", "bounceberry_sandwich", "stinarp_bucket_bucket", "bottleo_electricity", "tazegun", "electric_blossombush",
		"closed_electric_blossombush", "toxin_bladder_stagnation", "toxin_bladder_muscle_ache", "toxin_bladder_brittleness",
		"toxin_bladder_hallucinazium", "toxin_bladder_asphyxiation", "cupcake", "cupcake_stagnation", "cupcake_muscle_ache",
		"cupcake_brittleness", "cupcake_hallucinazium", "cupcake_asphyxiation", "music_disc_party", "sturdy_shells",
		"sturdy_shell_block", "sturdy_chestplate", "biting_shield", "shimmerworm_item", "shimmering_chrysalis",
		"end_dust", "vita_shroom", "mori_shroom", "purgatorial_mixture", "life_stew", "death_stew", "music_disc_reaper",
		"ancient_bone", "regenerative_flesh", "fungal_flesh", "vita_shroom_block", "mori_shroom_block", "ancient_skeleton_item",
		"ancient_skeleton_exhibit_item", "chiseled_mushroom_stem_eye", "chiseled_mushroom_stem_spiral", "chiseled_mushroom_stem_bird",
		"chiseled_mushroom_stem_mushroom", "chiseled_mushroom_stem_fire", "chiseled_mushroom_stem_thing", "fungal_staff",
		"explosive_jelly", "small_bomb_jelly_bucket", "medium_bomb_jelly_bucket", "large_bomb_jelly_bucket", "avoider_tail",
		"avoider_bucket_bucket", "avoider_fry_bucket_bucket", "booster_pump", "jelly_torpedo_item", "molded_shell",
		"iropod_bucket_bucket", "black_iropod_bucket_bucket", "iropod_helmet_helmet", "iroball_item", "blubber",
		"raw_blubberfish", "cooked_blubberfish", "critter_kebab", "blubberfish_bucket_bucket", "blubberfish_fry_bucket_bucket",
		"kelpire_rolls", "kelpire_roll_piece", "nauticrawl_tentacle", "shell_pieces", "nauticrawl_shell", "zombie_nauticrawl_shell",
		"nauticrawl_ramen", "nautical_helmet_helmet", "spiked_iroball", "nautical_axe", "music_disc_sails", "tooth_melter",
		"eerie_bark", "eerie_birch_log", "eerie_birch_wood", "eerie_dart", "birch_snow_cone", "black_resin_clump",
		"black_resin_brick", "black_resin_block", "black_resin_bricks", "black_resin_brick_stairs", "black_resin_brick_slab",
		"black_resin_brick_wall", "chiseled_black_resin_bricks", "spinal_fluid_bottle", "mysterious_virus_bottle",
		"lost_nerve", "cooked_nerve", "nerval_salad", "popped_nerval_mixture", "nervoid_brain", "decomposing_nervoid_brain",
		"rotten_nervoid_brain", "iced_nervoid_brain", "iced_decomposing_nervoid_brain", "iced_rotten_nervoid_brain",
		"ghostly_log", "ghostly_wood", "stripped_ghostly_log", "stripped_ghostly_wood", "ghostly_planks", "ghostly_mosaic_planks",
		"kelpy_ghostly_planks", "ghostly_stairs", "ghostly_slab", "ghostly_fence", "ghostly_fence_gate", "ghostly_door",
		"ghostly_trapdoor", "ghostly_pressure_plate", "ghostly_button", "wet_ghostly_planks", "wet_ghostly_mosaic_planks",
		"wet_kelpy_ghostly_planks", "petrified_ghostly_planks", "petrified_ghostly_mosaic_planks", "kelpy_petrified_ghostly_planks",
		"petrified_ghostly_stairs", "petrified_ghostly_slab", "ship_wheel", "ectometal", "ectometal_block", "ectometal_screw",
		"ectometal_nail", "thick_ectometal_screw", "ectometal_railing", "giant_chain", "barnacle_cluster", "corpse_barnacle",
		"dried_kelp_carpet", "fish_bone_block", "fish_bone_pole", "tattered_jolly_roger", "fish_bone", "tattered_cloth",
		"tattered_flag", "cutlass", "shark_tooth", "chattering_teeth_item", "rum_bottle", "tooth_syringe", "hardtack",
		"infested_hardtack", "hardtack_piece", "pearl", "treasure_key", "treasure_chest", "music_disc_grooveyard",
		"captains_heart", "corpse_parrot_item", "pirate_helmet", "pirate_chestplate", "pirate_leggings", "pirate_boots",
		"cannon", "cannon_ball", "infused_cannon_ball_cold", "infused_cannon_ball_fire", "infused_cannon_ball_slime",
		"infused_cannon_ball_electric", "infused_cannon_ball_combusting", "gravedigger_appendage", "grave_brush",
		"music_disc_waddle", "moss_clump", "glowing_ooze", "glowing_ooze_block", "cut_glowing_ooze_block", "goobulb",
		"ooze_rod", "ramchu_oil_bottle", "ramchu_bucket_bucket", "ramchu_bucket_no_shell_bucket", "ramchu_bucket_no_oil_bucket",
		"ramchu_fry_bucket_bucket", "dripper_remains", "dripstone_wall_mask", "slashklub", "custodian_core", "sculk_essence",
		"critterling_sack", "closed_critterling_sack", "critterling_sack_cubefrog", "critterling_sack_plainswyrm",
		"critterling_sack_dunger", "critterling_sack_snek", "critterling_sack_expy", "critterling_sack_scowl",
		"critterling_sack_rollball", "critterling_sack_opalcrab", "critterling_sack_mothkid", "critterling_sack_gillmunch",
		"critterling_sack_stalk", "critterling_sack_dominic", "critterling_sack_olmer", "critterling_sack_flarg",
		"critterling_sack_piranheed", "critterling_sack_mangotrice", "critterling_sack_fresnoid", "critterling_sack_cubefrog_rare",
		"critterling_sack_plainswyrm_rare", "critterling_sack_dunger_rare", "critterling_sack_snek_rare", "critterling_sack_expy_rare",
		"critterling_sack_scowl_rare", "critterling_sack_rollball_rare", "critterling_sack_opalcrab_rare", "critterling_sack_mothkid_rare",
		"critterling_sack_gillmunch_rare", "critterling_sack_stalk_rare", "critterling_sack_dominic_rare", "critterling_sack_olmer_rare",
		"critterling_sack_flarg_rare", "critterling_sack_piranheed_rare", "critterling_sack_mangotrice_rare", "critterling_sack_fresnoid_rare",
		"critterling_sack_cubefrog_epic", "critterling_sack_plainswyrm_epic", "critterling_sack_dunger_epic", "critterling_sack_snek_epic",
		"critterling_sack_expy_epic", "critterling_sack_scowl_epic", "critterling_sack_rollball_epic", "critterling_sack_opalcrab_epic",
		"critterling_sack_mothkid_epic", "critterling_sack_gillmunch_epic", "critterling_sack_stalk_epic", "critterling_sack_dominic_epic",
		"critterling_sack_olmer_epic", "critterling_sack_flarg_epic", "critterling_sack_piranheed_epic", "critterling_sack_mangotrice_epic",
		"critterling_sack_fresnoid_epic", "evolite", "evolite_block", "evolite_chandelier", "evolution_table",
		"fossil_display", "critter_fossil_1", "critter_fossil_2", "critter_fossil_3", "critter_fossil_4", "critter_fossil_5",
		"critter_fossil_6", "critter_fossil_7", "critter_fossil_8", "critter_fossil_9", "critter_fossil_10", "critterling_fossil_1",
		"critterling_fossil_2", "critterling_fossil_3", "plant_fossil_4", "plant_fossil_1", "plant_fossil_2", "plant_fossil_3",
		"fossil_block", "deepslate_fossil_block", "fungal_zombie_spawn_doll", "frightshroom_spawn_doll", "rot_zombie_spawn_doll",
		"nightshroom_spawn_doll", "zombie_nauticrawl_spawn_doll", "corpse_mate_spawn_doll", "corpse_quartermaster_spawn_doll",
		"corpse_tank_spawn_doll", "corpse_lookout_spawn_doll", "corpse_captain_spawn_doll", "corpse_parrot_spawn_doll",
		"amalgam_spawn_doll", "ancient_custodian_spawn_doll", "tab_icon");

	private MoreCrittersTabContents() {}
}
